// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

// Defines values for AddressCheckStatus.
const (
	AddressCheckStatusAddressUnresolved   AddressCheckStatus = "address_unresolved"
	AddressCheckStatusEligible            AddressCheckStatus = "eligible"
	AddressCheckStatusGeocoderUnavailable AddressCheckStatus = "geocoder_unavailable"
	AddressCheckStatusOutsideDeliveryZone AddressCheckStatus = "outside_delivery_zone"
)

// Valid indicates whether the value is a known member of the AddressCheckStatus enum.
func (e AddressCheckStatus) Valid() bool {
	switch e {
	case AddressCheckStatusAddressUnresolved:
		return true
	case AddressCheckStatusEligible:
		return true
	case AddressCheckStatusGeocoderUnavailable:
		return true
	case AddressCheckStatusOutsideDeliveryZone:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	Usd Currency = "usd"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case Usd:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAddressUnresolved   ErrorCode = "address_unresolved"
	ErrorCodeCheckoutUnavailable ErrorCode = "checkout_unavailable"
	ErrorCodeGeocoderUnavailable ErrorCode = "geocoder_unavailable"
	ErrorCodeInvalidOrder        ErrorCode = "invalid_order"
	ErrorCodeMenuItemUnavailable ErrorCode = "menu_item_unavailable"
	ErrorCodeOutsideHours        ErrorCode = "outside_hours"
	ErrorCodePaymentUnavailable  ErrorCode = "payment_unavailable"
	ErrorCodeServiceOff          ErrorCode = "service_off"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAddressUnresolved:
		return true
	case ErrorCodeCheckoutUnavailable:
		return true
	case ErrorCodeGeocoderUnavailable:
		return true
	case ErrorCodeInvalidOrder:
		return true
	case ErrorCodeMenuItemUnavailable:
		return true
	case ErrorCodeOutsideHours:
		return true
	case ErrorCodePaymentUnavailable:
		return true
	case ErrorCodeServiceOff:
		return true
	default:
		return false
	}
}

// AddressCheck defines model for AddressCheck.
type AddressCheck struct {
	Address          string             `json:"address"`
	CheckoutEligible bool               `json:"checkout_eligible"`
	FormattedAddress string             `json:"formatted_address,omitempty"`
	Status           AddressCheckStatus `json:"status"`
}

// AddressCheckRequest defines model for AddressCheckRequest.
type AddressCheckRequest struct {
	Address string `json:"address"`
}

// AddressCheckStatus defines model for AddressCheckStatus.
type AddressCheckStatus string

// CreateOrderItemRequest defines model for CreateOrderItemRequest.
type CreateOrderItemRequest struct {
	DrinkSlug     string `json:"drink_slug"`
	Modifications string `json:"modifications,omitempty"`
	Quantity      int    `json:"quantity"`
	ShopSlug      string `json:"shop_slug"`
	Size          string `json:"size"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Address       string                   `json:"address"`
	Company       string                   `json:"company"`
	CustomerNote  string                   `json:"customer_note,omitempty"`
	DeliveryNotes string                   `json:"delivery_notes,omitempty"`
	Email         string                   `json:"email"`
	Items         []CreateOrderItemRequest `json:"items"`
	Name          string                   `json:"name"`
	Phone         string                   `json:"phone,omitempty"`
}

// CreateOrderResponse defines model for CreateOrderResponse.
type CreateOrderResponse struct {
	AddressCheck      AddressCheck `json:"address_check"`
	CheckoutSessionID string       `json:"checkout_session_id,omitempty"`
	CheckoutURL       string       `json:"checkout_url,omitempty"`
	Order             OrderSummary `json:"order"`
}

// Currency defines model for Currency.
type Currency string

// Drink defines model for Drink.
type Drink struct {
	Description string      `json:"description"`
	Name        string      `json:"name"`
	Sizes       []SizePrice `json:"sizes"`
	Slug        string      `json:"slug"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  ErrorCode `json:"code,omitempty"`
	Error string    `json:"error"`
}

// Menu defines model for Menu.
type Menu struct {
	Description string `json:"description"`
	Shops       []Shop `json:"shops"`
	Title       string `json:"title"`
}

// OrderSummary defines model for OrderSummary.
type OrderSummary struct {
	Currency      Currency `json:"currency"`
	ID            string   `json:"id"`
	Status        string   `json:"status"`
	SubtotalCents int      `json:"subtotal_cents"`
	TotalCents    int      `json:"total_cents"`
	ZoneStatus    string   `json:"zone_status"`
}

// ServiceStatus defines model for ServiceStatus.
type ServiceStatus struct {
	CheckoutAvailable bool   `json:"checkout_available"`
	CloseTime         string `json:"close_time"`
	OpenTime          string `json:"open_time"`
	Reason            string `json:"reason,omitempty"`
	ServiceEnabled    bool   `json:"service_enabled"`
}

// Shop defines model for Shop.
type Shop struct {
	Drinks []Drink   `json:"drinks"`
	Hours  ShopHours `json:"hours"`
	Name   string    `json:"name"`
	Slug   string    `json:"slug"`
}

// ShopHours defines model for ShopHours.
type ShopHours struct {
	CloseTime     string `json:"close_time"`
	LastOrderTime string `json:"last_order_time"`
	OpenTime      string `json:"open_time"`
}

// SizePrice defines model for SizePrice.
type SizePrice struct {
	Currency   Currency `json:"currency"`
	Name       string   `json:"name"`
	PriceCents int      `json:"price_cents"`
}

// Error defines model for Error.
type Error = ErrorResponse

// CheckAddressJSONRequestBody defines body for CheckAddress for application/json ContentType.
type CheckAddressJSONRequestBody = AddressCheckRequest

// CreateCoffeeOrderJSONRequestBody defines body for CreateCoffeeOrder for application/json ContentType.
type CreateCoffeeOrderJSONRequestBody = CreateOrderRequest
